---
- name: "install dependencies"
  ansible.builtin.apt:
    pkg:
      - curl
      - tar
      - wget
      - aria2
      - clang 
      - pkg-config
      - libssl-dev
      - jq
      - build-essential
      - git
      - make
      - ncdu
    state: latest
    update_cache: true
