---
- name: Download and install from release
  get_url:
    url: "{{ release_url }}/v{{ version }}/celestia-app_Linux_x86_64.tar.gz"
    dest: "/tmp/celestia-app.tar.gz"

- name: Extract celestia-app
  unarchive:
    src: "/tmp/celestia-app.tar.gz"
    dest: "/tmp/"
    remote_src: yes

- name: Move celestia-app binary to /usr/local/bin
  command: mv /tmp/celestia-appd /usr/local/bin/
  args:
    creates: /usr/local/bin/celestia-appd
