---
- include_tasks: dependencies.yml
- include_tasks: install.yml
- include_tasks: configure.yml
  when: node_type != "validator"
- include_tasks: configure_validator.yml
  when: node_type == "validator"
- include_tasks: service.yml
