---
- name: create systemd service unit file
  template:
    src: systemd.service.j2
    dest: /etc/systemd/system/celestia-appd.service
  vars:
    HOME_DIR: "{{ home_dir }}"
  notify:
    - Reload systemd

- name: Start celestia app service
  service:
    name: celestia-appd
    state: started
    enabled: yes
